"""Initial migration

Revision ID: 978cd69e9e3a
Revises: 
Create Date: 2025-02-06 16:44:43.746262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978cd69e9e3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
